"""
Synthetic Spanish support ticket dataset.
"""
SYNTHETIC_TICKETS = [
    {
        "id": "TKT-001",
        "subject": "Error al procesar pago",
        "body": "Hola, intenté pagar mi factura pero la transacción fue rechazada. Mi tarjeta está activa y tiene fondos. Necesito resolver esto urgentemente para evitar la suspensión del servicio.",
        "category": "facturación",
        "urgency": 2,
        "needs_human": True,
    },
    {
        "id": "TKT-002",
        "subject": "Consulta sobre plan premium",
        "body": "Buenos días, me gustaría saber cuáles son las ventajas del plan premium y cuánto cuesta. También quiero saber si hay descuentos para empresas.",
        "category": "ventas",
        "urgency": 0,
        "needs_human": False,
    },
    {
        "id": "TKT-003",
        "subject": "La aplicación se cierra sola",
        "body": "Desde ayer la aplicación se cierra automáticamente cuando intento abrir un documento. Ya reinicié el teléfono pero el problema persiste. Uso iPhone 13 con iOS 17.",
        "category": "técnico",
        "urgency": 1,
        "needs_human": True,
    },
    {
        "id": "TKT-004",
        "subject": "Quiero cancelar mi suscripción",
        "body": "No estoy satisfecho con el servicio. Quiero cancelar mi suscripción y solicitar un reembolso completo. He sido cliente por 2 semanas y no funciona como prometieron.",
        "category": "cancelación",
        "urgency": 1,
        "needs_human": True,
    },
    {
        "id": "TKT-005",
        "subject": "Cambio de correo electrónico",
        "body": "Hola, cambié de trabajo y necesito actualizar el correo electrónico de mi cuenta. ¿Cómo puedo hacerlo?",
        "category": "otro",
        "urgency": 0,
        "needs_human": False,
    },
    {
        "id": "TKT-006",
        "subject": "Cobro duplicado en mi tarjeta",
        "body": "¡URGENTE! Me cobraron dos veces por el mismo mes. Necesito que devuelvan el cobro duplicado HOY o haré un contracargo con mi banco. Esto es inaceptable.",
        "category": "facturación",
        "urgency": 2,
        "needs_human": True,
    },
    {
        "id": "TKT-007",
        "subject": "No puedo iniciar sesión",
        "body": "Olvidé mi contraseña y el enlace de recuperación no llega a mi correo. ¿Pueden ayudarme?",
        "category": "técnico",
        "urgency": 1,
        "needs_human": False,
    },
    {
        "id": "TKT-008",
        "subject": "¿Cuándo estará disponible la función X?",
        "body": "Leí en el blog que lanzarían una nueva función de reportes. ¿Cuándo estará disponible? Sería muy útil para nuestro equipo.",
        "category": "otro",
        "urgency": 0,
        "needs_human": False,
    },
    {
        "id": "TKT-009",
        "subject": "Error 500 al exportar datos",
        "body": "Cada vez que intento exportar los datos del último mes obtengo un error 500. Necesito esos datos para una auditoría que vence mañana.",
        "category": "técnico",
        "urgency": 2,
        "needs_human": True,
    },
    {
        "id": "TKT-010",
        "subject": "Información sobre facturación corporativa",
        "body": "Somos una empresa con 50 empleados y queremos información sobre planes corporativos, métodos de pago y facturación centralizada.",
        "category": "ventas",
        "urgency": 0,
        "needs_human": True,
    },
    {
        "id": "TKT-011",
        "subject": "Servicio deficiente - quiero hablar con un supervisor",
        "body": "Llevo 3 días intentando resolver un problema y nadie me ha ayudado. Exijo hablar con un supervisor INMEDIATAMENTE. Si no resuelven esto hoy, cancelaré y dejaré reseñas negativas.",
        "category": "cancelación",
        "urgency": 2,
        "needs_human": True,
    },
    {
        "id": "TKT-012",
        "subject": "¿Aceptan PayPal?",
        "body": "Hola, quiero suscribirme pero solo tengo PayPal. ¿Es un método de pago aceptado?",
        "category": "facturación",
        "urgency": 0,
        "needs_human": False,
    },
    {
        "id": "TKT-013",
        "subject": "Los datos no se sincronizan entre dispositivos",
        "body": "Modifico un documento en mi laptop pero los cambios no aparecen en mi tablet. Ya verifiqué que ambos están conectados a internet.",
        "category": "técnico",
        "urgency": 1,
        "needs_human": False,
    },
    {
        "id": "TKT-014",
        "subject": "Felicitaciones por el nuevo diseño",
        "body": "Solo quería escribir para felicitarlos por la actualización de la interfaz. Se ve mucho mejor y es más fácil de usar. ¡Buen trabajo!",
        "category": "otro",
        "urgency": 0,
        "needs_human": False,
    },
    {
        "id": "TKT-015",
        "subject": "Solicitud de reembolso",
        "body": "Pagué por 3 meses pero solo usé el servicio 1 mes. Quiero cancelar y solicito el reembolso proporcional de los 2 meses restantes.",
        "category": "facturación",
        "urgency": 1,
        "needs_human": True,
    },
    {
        "id": "TKT-016",
        "subject": "¿Tienen API disponible?",
        "body": "Soy desarrollador y necesito integrar su servicio con nuestra plataforma. ¿Tienen documentación de API?",
        "category": "técnico",
        "urgency": 0,
        "needs_human": False,
    },
    {
        "id": "TKT-017",
        "subject": "Descuento para estudiantes",
        "body": "Soy estudiante universitario. ¿Ofrecen descuentos para estudiantes? Puedo enviar mi credencial.",
        "category": "ventas",
        "urgency": 0,
        "needs_human": False,
    },
    {
        "id": "TKT-018",
        "subject": "CRÍTICO: Sistema caído completamente",
        "body": "URGENTE: El sistema está completamente caído. Ninguno de nuestros 200 empleados puede acceder. Esto está paralizando nuestra operación. Necesitamos solución INMEDIATA.",
        "category": "técnico",
        "urgency": 2,
        "needs_human": True,
    },
    {
        "id": "TKT-019",
        "subject": "Propuesta de partnership",
        "body": "Represento a una empresa de tecnología y nos gustaría explorar oportunidades de partnership. ¿Con quién puedo hablar sobre alianzas estratégicas?",
        "category": "ventas",
        "urgency": 1,
        "needs_human": True,
    },
    {
        "id": "TKT-020",
        "subject": "Excelente soporte técnico",
        "body": "Quiero agradecer a Juan del equipo de soporte. Resolvió mi problema en minutos y fue muy amable. ¡Excelente servicio!",
        "category": "otro",
        "urgency": 0,
        "needs_human": False,
    },
]
